# this is a example that was used in class
version: '3'
services:
  ps:
    container_name: ps_container
    image: d8a
    privileged: true
    environment:
     - DISPLAY=${DISPLAY} 
    volumes:
      - ./../../:/root/PS
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/localtime:/etc/localtime

    network_mode: host
    stdin_open: true
    tty: true
